# Generated by Django 5.2.4 on 2025-07-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminalLine',
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Skill category', 'verbose_name_plural': 'Skill categorys'},
        ),
        migrations.AlterModelOptions(
            name='techstackitem',
            options={'verbose_name': 'Tech stack item', 'verbose_name_plural': 'Tech stack items'},
        ),
    ]
