# Generated by Django 5.2.4 on 2025-07-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_terminalline_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstackitem',
            options={'ordering': ['order'], 'verbose_name': 'Tech stack item', 'verbose_name_plural': 'Tech stack items'},
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='techstackitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
