name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /mnt/portfolio
          export GIT_SSH_COMMAND='ssh -i /mnt/github_deploy_key -o IdentitiesOnly=yes'
          export DOCKER_BUILDKIT=1
          
          git remote set-url origin git@github.com:W-Mirshod/portfolio.git
          git fetch origin
          git reset --hard origin/master
          git clean -fd
          
          npm install tsparticles
          
          docker-compose build
          if docker-compose ps | grep -q portfolio; then
            docker-compose down
          fi
          docker-compose up -d --build
