name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /mnt/portfolio
          export GIT_SSH_COMMAND='ssh -i /mnt/github_deploy_key -o IdentitiesOnly=yes'
          git fetch origin
          git reset --hard origin/master
          git clean -fd
          git pull
          docker-compose build
          if docker-compose run --rm app true; then
            docker-compose down || true
            docker-compose up -d --build
          else
            echo 'Build failed, keeping existing running container.'
          fi
